package com.thera.theratime.service;

import com.thera.theratime.model.Timesheet;
import com.thera.theratime.model.User;
import com.thera.theratime.repository.TimesheetRepository;
import com.thera.theratime.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class PayrollService {

    @Autowired
    private TimesheetRepository timesheetRepository;

    @Autowired
    private UserRepository userRepository;

    public Map<String, Object> generatePayrollPayload() {
        List<User> users = userRepository.findAll();
        List<Map<String, Object>> employeeData = new ArrayList<>();

        for (User user : users) {
            List<Timesheet> timesheets = timesheetRepository.findByUserId(user.getId());
            // Filter for current pay period (simplified: all approved timesheets)
            List<Timesheet> approved = timesheets.stream()
                    .filter(t -> t.getStatus() == Timesheet.Status.APPROVED)
                    .collect(Collectors.toList());

            double totalHours = approved.stream().mapToDouble(Timesheet::getHours).sum();
            
            // Simplified breakdown logic
            double regularHours = totalHours; // Assuming no overtime logic for MVP unless > 40h/week implemented
            double overtimeHours = 0.0;
            
            // If we want simple daily overtime > 8h
            double dailyRegular = 0;
            double dailyOvertime = 0;
            for(Timesheet t : approved) {
                if(t.getHours() > 8) {
                    dailyRegular += 8;
                    dailyOvertime += (t.getHours() - 8);
                } else {
                    dailyRegular += t.getHours();
                }
            }
            regularHours = dailyRegular;
            overtimeHours = dailyOvertime;

            double grossPay = (regularHours * user.getRate()) + (overtimeHours * user.getRate() * 1.5);

            Map<String, Object> employee = new LinkedHashMap<>();
            employee.put("employeeId", "EMP-" + (1000 + user.getId()));
            employee.put("legalName", user.getName());
            employee.put("email", user.getEmail());
            employee.put("employmentType", user.getRole().toString()); // CONTRACTOR/MANAGER
            employee.put("currency", "USD");
            employee.put("totalHours", totalHours);

            Map<String, Object> breakdown = new LinkedHashMap<>();
            breakdown.put("regularHours", regularHours);
            breakdown.put("overtimeHours", overtimeHours);
            breakdown.put("doubleTimeHours", 0.0);
            breakdown.put("ptoHours", 0.0);
            breakdown.put("sickHours", 0.0);
            employee.put("breakdown", breakdown);

            employee.put("rate", user.getRate());
            employee.put("estimatedGrossPay", grossPay);
            employee.put("notes", "Generated by TheraTime");

            employeeData.add(employee);
        }

        Map<String, Object> payload = new LinkedHashMap<>();
        Map<String, Object> meta = new LinkedHashMap<>();
        meta.put("source", "TheraTime Microservice");
        meta.put("timestamp", new Date()); // Or ISO string
        meta.put("payPeriod", Map.of("startDate", "2024-11-01", "endDate", "2024-11-15")); // Mock dates
        meta.put("batchId", "BATCH-" + System.currentTimeMillis());
        meta.put("approverEmail", "akhil@getthera.com");
        
        payload.put("meta", meta);
        payload.put("data", employeeData);

        return payload;
    }
}
